### ISSUE TITLE
Contact Info

### ISSUE THREAD

**Issue by dr3adx** [grypesc/PixiJS-NodeJS-GameOnly#2]
Hello, I have a business offer for you, do you have Discord/Skype where we can talk?

Had to post this on issues as I didn't see other way to contact u.

Thanks.

**Comment by grypesc** [comment]
> Hello, I have a business offer for you, do you have Discord/Skype where we can talk?
> 
> Had to post this on issues as I didn't see other way to contact u.
> 
> Thanks.

Hello, yes, my Discord id is Greg#0345
I am also on Facebook :)
